apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendcors
  labels:
    app: backendcors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendcors
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: 'true'
      labels:
        app: backendcors
    spec:
      containers:
        - name: backendcors
          image: sameermosesmurala/backendcors
          ports:
            - containerPort: 8082