apiVersion: apps/v1
kind: Deployment
metadata:
  name: springtempo
  labels:
    app: springtempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springtempo
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: 'true'
        sidecar.opentelemetry.io/inject: 'true'
      labels:
        app: springtempo
    spec:
      containers:
        - name: springtempo
          image: sameermosesmurala/springtempo
          ports:
            - containerPort: 8082