apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendkafka
  labels:
    app: backendkafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendkafka
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: 'true'
      labels:
        app: backendkafka
    spec:
      containers:
        - name: backendkafka
          image: sameermosesmurala/backendkafka
          ports:
            - containerPort: 8082