version: '3.1'
services:
  ms-one:
    container_name: ms-one
    build:
      context: ./ms-one
      dockerfile: Dockerfile
    environment:
      - OTEL_SERVICE_NAME=ms-one
      - OTEL_EXPORTER=otlp_span
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
    ports:
      - "8082:8082"