version: '3.1'
services:
  backend:
    container_name: telemtry-app
    build:
      dockerfile: Dockerfile
    environment:
      - OTEL_SERVICE_NAME=ms-one
      - OTEL_EXPORTER=otlp_span
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
      - JAVA_OPTS=-javaagent:/opentelemetry-javaagent.jar
    ports:
      - "8082:8082"