version: "2"
services:

  hotrod:
    image: sameermosesmurala/backendspringtelemetry2:latest
    ports:
      - "8082:8082"

    # Collector
  collector-gateway:
    image: otel/opentelemetry-collector:0.29.0
    volumes:
      - ./collector-gateway.yaml:/etc/collector-gateway.yaml
    command: [ "--config=/etc/collector-gateway.yaml" ]
    ports:
      - "4317:4317"        # OTLP gRPC receiver
      - "4318:4318"        # OTLP HTTP receiver