version: '3.1'
services:
  backendjava:
    container_name: backendjava
    build:
      dockerfile: Dockerfile
    environment:
      - OTEL_SERVICE_NAME=backendapp
      - OTEL_EXPORTER=otlp_span,prometheus
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=service.name=backendapp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://20.55.244.67:9092/topics/SAMPLE_TOPIC
      - JAVA_OPTS=-javaagent:/opentelemetry-javaagent.jar
    ports:
      - "8082:8082"