version: '3.1'
services:
  backendspringtelemetry3:
    container_name: backendspringtelemetry3
    build:
      dockerfile: Dockerfile
    environment:
      - OTEL_SERVICE_NAME=backendapp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER=otlp_span,prometheus
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=service.name=backendapp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://20.22.168.207:4317
      - JAVA_OPTS=-javaagent:/opentelemetry-javaagent.jar
    ports:
      - "8082:8082"