version: '3.1'
services:
  springapp:
    container_name: springtelemetryapp
    build:
      dockerfile: Dockerfile
    environment:
      - OTEL_SERVICE_NAME=backendapp
      - OTEL_EXPORTER=otlp_span
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://20.22.145.68:4317
      - JAVA_OPTS=-javaagent:/opentelemetry-javaagent.jar
    ports:
      - "8082:8082"